{% set name = "zcollection" %}
{% set version = "2024.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2b3fa26f7d9638c75413ac6bc07d07a103bc105dddc3e37d367e8a0109c10cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  # All dependencies are required until we change the way the
  # version number and file are generated.
  host:
    - python {{ python_min }}
    - setuptools >=45
    - pip
  run:
    - python >={{ python_min }}
    - dask-core >=2022.8.0
    - distributed
    - fasteners
    - fsspec
    - numcodecs
    - numpy >=1.20
    - xarray
    - zarr >=2.11

test:
  requires:
    - pytest
    - pyarrow
    - s3fs
    - python {{ python_min }}
  commands:
    - pytest --pyargs zcollection

about:
  home: https://github.com/CNES/zcollection
  summary: Handle a collection of Zarr groups
  description: |
    This project is a Python library manipulating data split into a collection of groups stored in Zarr format.
    This collection allows dividing a dataset into several partitions to facilitate acquisitions or updates made
    from new products. Possible data partitioning is: by date (hour, day, month, etc.)
    or by sequence.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://zcollection.readthedocs.io/en/latest/
  dev_url: https://github.com/CNES/zcollection

extra:
  recipe-maintainers:
    - fbriol
    - Thomas-Z
